### ISSUE TITLE
Write logs to `stderr`

### ISSUE THREAD

**Issue by lxgr-linux** [talwat/indiepkg#4]
**Bug description**:
Not a real "Bug" but more a thing that should not happen.
All logging information is written to `stdout`, that's bad because when another script or program wants to utilize indiepkg it will be faced with a lot of logging clutter to comprehend. So the best way is to write all logging to `stderr` and just write the desired information like in the case of the `info` or `search` command the actual pkg information to `stdout`.

Another possibility would be to add a commandline option like `quiet` or `-q` that suppresses all unnecessary logging.
**Steps to reproduce the behavior**:

**Expected behavior**:
Logging should be written to `stderr`

**Screenshots**:

**Enviorment**
 - OS: Arch Linux
 - IndiePKG Version: testing

**Additional context**:

**Comment by talwat** [comment]
I'm basically using the built-in go logging functions (with some styling hence my own `log()` function), but I might try and make the **error** messages write to stderr.

**Comment by talwat** [comment]
I think a solution is to make a few commands specifically designed to be used in scripts, and other commands designed to be used by the user.

**Comment by talwat** [comment]
Two of those commands have now been made, and I will definitely add new commands intended for scripting in the future.
